### ISSUE TITLE
Follow automatic-pancake

### ISSUE THREAD

**Issue by helio-frota** [bucharest-gold/fidelity#12]
- [x] Readme https://github.com/bucharest-gold/automatic-pancake/issues/5#issuecomment-245017883
- [x] Tools - istanbul, semistandard eslint stuff, tape, tap-spec, etc [if applicable - genet, bench...] https://github.com/bucharest-gold/automatic-pancake/blob/master/package.json#L23-L33
- [x] Contributing guide https://github.com/bucharest-gold/automatic-pancake/blob/master/CONTRIBUTING.md
- [x] ES6 with our current techniques

**Comment by lance** [comment]
@helio-frota Can you be more specific about what items need to be changed, added or removed in order to be more compliant?
