### ISSUE TITLE
Produce a browser compatible version for releases

### ISSUE THREAD

**Issue by lance** [bucharest-gold/fidelity#5]
I don't think there is any reason to limit this module to node.js

**Comment by lholmquist** [comment]
I think this makes sense.  Looks like Class is well supported in modern browsers now. 

It would be interesting to see the benchmarks on a mobile device

**Comment by lance** [comment]
Initial pass on this branch https://github.com/bucharest-gold/fidelity/tree/browserify

There's something going on with setTimeout that is causing a number of tests to fail within the browser.
